### PR TITLE
Fix request logger again

### PR DESCRIPTION
**Pull request by tony-spataro-rs**

### CODE REVIEW

**Comment by shaley91** [comment]
LGTM @tony-spataro-rs.  Thanks for the quick turn around.  Looks like the specs are failing.

**Comment by tony-spataro-rs** [comment]
That's an occasional timing bug in the functional tests of the request
balancer (it uses timing as a test criterion, sucky but we couldn't find
any other way to do it at the time.)

I'll merge to master and push a new gem version presently.

Cheers,
    Tony

**Comment by shaley91** [comment]
@tony-spataro-rs any update on this?

**Comment by tony-spataro-rs** [comment]
@shaley91 Pushed 2.8.44 just now

**Pull request merged**
