### PR TITLE
Allow the closing of the syslog

### PR DESCRIPTION
**Pull request by CallumD**
This is so that we can open the syslog again with a different file name.

We are looking to use this in CA for delayed jobs to write to files with
the same name as the job. Please see
analytics_data_service pr 262 for
details of how we are doing this.

As we are using a global variable this is not thread safe. This also
assumes that no other code we are using assumes no side affect from
calling close.

### CODE REVIEW

**Comment by CallumD** [comment]
@smcgivern also helped with this

**Comment by tony-spataro-rs** [comment]
Would it be better if we left `#close` as a no-op, and instead reopened syslog in `#initialize` if necessary? Something like:
    def initialize(...)
      @@mutex.synchronize do
        if @@syslog && (@@program_name  != program_name)
          @@syslog.close ; @@syslog = nil
        end
        
        @@syslog ||= # proceed with making new syslog object if necessary
      end
    end

This lets existing instances of SystemLogger continue to function (with the new program name) instead of blowing up with `NoMethodError` after calling `NilClass#whatever`.

Note that I also added thread safety in my example, but that's ancillary.

**Comment by CallumD** [comment]
@tony-spataro-rs CR changes made. Let me know if your happy and I will push a version bump commit

**Comment by CallumD** [comment]
Looks like this is no `@@mutex` defined?

**Comment by tony-spataro-rs** [comment]
You're right; we need to do a one-time initialization of @@mutex in the class definition

**Comment by tony-spataro-rs** [comment]
LGTM :shipit: !

**Comment by smcgivern** [comment]
This is the best version bump commit I've ever seen; looks good.

**Comment by CallumD** [comment]
:)

**Pull request merged**
