### PR TITLE
Fix method signature of Multiplexer#respond_to?

### PR DESCRIPTION
**Pull request by smcgivern**
Object#respond_to? takes an optional second argument; don't blow up when it's present.

<http://ruby-doc.org/core-2.2.1/Object.html#method-i-respond_to-3F>

### CODE REVIEW

**Comment by smcgivern** [comment]
This is actually used by RSpec, which is what broke for us (expectation on a log message, just switched to having a multiplexing logger in test mode for Reasons).

https://github.com/rspec/rspec-mocks/blob/master/lib/rspec/mocks/method_reference.rb#L97

The arity of this method is also wrong in two other places, but I'm not sure if those are used any more:
* https://github.com/rightscale/right_support/blob/master/lib/right_support/crypto/signed_hash.rb#L189
* https://github.com/rightscale/right_support/blob/master/lib/right_support/ruby/easy_singleton.rb#L36

**Comment by tony-spataro-rs** [comment]
Good catch. We should also define `respond_to_missing?` if we want to be 100% correct.

https://robots.thoughtbot.com/always-define-respond-to-missing-when-overriding

**Comment by smcgivern** [comment]
OK, added that too for all three. Let me know if it you need any more changes, otherwise I'll squash and reword the commit.

**Comment by smcgivern** [comment]
I don't think the failing spec on the push build is my fault :smiley:

**Comment by tony-spataro-rs** [comment]
LGTM; the failing build is due to some timing-based cukes that I never found a way to implement without looking at the clock.

**Pull request merged**
